### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by qingchunlizhi** [maxorange/pix2vox#9]
/home/duan/anaconda3/envs/venv/lib/python2.7/site-packages/qdarkstyle/__init__.py:181: FutureWarning: load_stylesheet() will not receive pyside parameter in version 3. Set QtPy environment variable to specify the Qt binding insteady.
  FutureWarning
Traceback (most recent call last):
  File "/home/duan/pix2vox/ui/gui_main.py", line 115, in <lambda>
    slider.valueChanged.connect(lambda value, j=int(index): self.opt_engine.set_label(float(value)/100, j))
  File "/home/duan/pix2vox/opt/constrained_opt.py", line 59, in set_label
    self.update_voxel_model()
  File "/home/duan/pix2vox/opt/constrained_opt.py", line 42, in update_voxel_model
    self.preprocess_constraints()
  File "/home/duan/pix2vox/opt/constrained_opt.py", line 35, in preprocess_constraints
    color_old, edge_old = self.constraints
TypeError: 'NoneType' object is not iterable

I don‘t know whether it is caused by the data?

**Comment by maxorange** [comment]
Hi qingchunlizhi
This source code is a bit old, so it is possibly caused by some python packages.
Which version of python are you using? 2.x or 3.x?

**Comment by kakoedlinnoe** [comment]
python 2.x

**Comment by purplepeach29** [comment]
I am getting the same error. Was the issue resolved?

**Comment by maxorange** [comment]
This code is a bit old so I'm thinking of updating it.

**Comment by purplepeach29** [comment]
If you could update it sooner, that would be of great help.
Thank you.

**Comment by wizard499** [comment]
I m getting the same error kindly update the code as soon as possible.
thank you in advance.

**Comment by wizard499** [comment]
> /home/duan/anaconda3/envs/venv/lib/python2.7/site-packages/qdarkstyle/**init**.py:181: FutureWarning: load_stylesheet() will not receive pyside parameter in version 3. Set QtPy environment variable to specify the Qt binding insteady.
> FutureWarning
> Traceback (most recent call last):
> File "/home/duan/pix2vox/ui/gui_main.py", line 115, in
> slider.valueChanged.connect(lambda value, j=int(index): self.opt_engine.set_label(float(value)/100, j))
> File "/home/duan/pix2vox/opt/constrained_opt.py", line 59, in set_label
> self.update_voxel_model()
> File "/home/duan/pix2vox/opt/constrained_opt.py", line 42, in update_voxel_model
> self.preprocess_constraints()
> File "/home/duan/pix2vox/opt/constrained_opt.py", line 35, in preprocess_constraints
> color_old, edge_old = self.constraints
> TypeError: 'NoneType' object is not iterable
> 
> I don‘t know whether it is caused by the data?

Did you found the solution yet? If so, kindly share!
